//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("OpenIso8583.Net")]
[assembly: AssemblyDescription("ISO8583 Message Builder")]
[assembly: AssemblyCompany("John Oxley")]
[assembly: AssemblyProduct("OpenIso8583.Net")]
[assembly: AssemblyCopyright("Copyright © John Oxley 2011")]
[assembly: ComVisible(false)]
[assembly: Guid("dad698b7-4ada-4f02-8446-12fe960fa2e1")]
[assembly: AssemblyVersion("0.5.0.0")]
[assembly: AssemblyFileVersion("0.5.0.0")]


